//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.leave_entitlement = new HashSet<leave_entitlement>();
            this.users = new HashSet<user>();
            this.leaves = new HashSet<leave>();
        }
    
        public int EmployeeID { get; set; }
        public string EmpCode { get; set; }
        public string SurName { get; set; }
        public string OtherNames { get; set; }
        public Nullable<System.DateTime> DateOfEmployment { get; set; }
        public bool IsDisengaged { get; set; }
    
        public virtual ICollection<leave_entitlement> leave_entitlement { get; set; }
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<leave> leaves { get; set; }
    }
}
