//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leave.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeaveEntities : DbContext
    {
        public LeaveEntities()
            : base("name=LeaveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<leave_entitlement> leave_entitlement { get; set; }
        public virtual DbSet<leave_type> leave_type { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<leave_period> leave_period { get; set; }
        public virtual DbSet<leave> leaves { get; set; }
        public virtual DbSet<error> errors { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
    }
}
