//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave
    {
        public int id { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public double days { get; set; }
        public string comments { get; set; }
        public int leave_type_id { get; set; }
        public int employee_id { get; set; }
        public Nullable<System.DateTime> date_applied { get; set; }
        public int period_id { get; set; }
        public Nullable<double> half_days { get; set; }
        public Nullable<bool> work_weekends { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual leave_period leave_period { get; set; }
        public virtual leave_type leave_type { get; set; }
    }
}
