//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string passwordsalt { get; set; }
        public int role_id { get; set; }
        public byte status { get; set; }
    
        public virtual user_role user_role { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
